randn('seed',123)
x(1:524) = 0;
x_temp = randn(1, 512);
x(13:524) = x_temp;
y(1:512) = 0;
n = 0;
x1 = 0.5;
x2 = x1 - x1*2.0^-2.0;
x3 = x2 + x1*2.0^-5.0;
x4 = x3 + x1*2.0^-7.0;
x5 = x4 + x1*2.0^-9.0;
x6 = x5 + x1*2.0^-14.0;
coef_temp(1) = x6*2.0^-2.0;
coef_temp(2) = x1*2.0^-8.0+x1*2.0^-10.0+x1*2.0^-12.0+x1*2.0^-15.0;
coef_temp(3) =-x2*2.0^-2.0+x1*2.0^-6.0+x2*2.0^-8.0-x1*2.0^-12.0+x1*2.0^-16.0;
coef_temp(4) =-x2*2.0^-3.0 + x2*2.0^-9.0 + x1*2.0^-14.0;
coef_temp(5) =x2*2.0^-1.0 - x1*2.0^-5.0 - x1*2.0^-10.0 - x1*2.0^-15.0;
coef_temp(6) =x2 + x1*2.0^-4.0 + x1*2.0^-6.0 - x1*2.0^-9.0 - x2*2.0^-13.0;
for n = 13:183 
       y(3*n-38) = quantizer_input(x(3*n-26))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(3*n-27))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-28))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-29))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-30))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-31))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-32))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-33))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-34))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-35))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-36))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-37))*quantizer_coef(coef_temp(1));
        y(3*n-37) = quantizer_input(x(3*n-25))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(3*n-26))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-27))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-28))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-29))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-30))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-31))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-32))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-33))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-34))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-35))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-36))*quantizer_coef(coef_temp(1));
        y(3*n-36) = quantizer_input(x(3*n-26))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(3*n-27))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-28))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-29))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-30))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-31))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-32))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(3*n-33))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(3*n-34))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(3*n-35))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(3*n-36))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(3*n-37))*quantizer_coef(coef_temp(1));
end
y_1st = y(1)
y_100st = y(100)
y_200st = y(200)