randn('seed',123)
x(1:525) = 0;
x_temp = randn(1, 512);
x(13:524) = x_temp;
n = 0;
coef_temp = [0.098891890744637 0.002579421311410 -0.084589441437739 -0.047578154855338 0.179439401283587 ...
    0.413044584947859];
for n = 13:140
        y(4*n-51) = quantizer_input(x(4*n-39))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(4*n-40))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-41))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-42))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-43))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-44))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-45))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-46))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-47))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-48))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-49))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-50))*quantizer_coef(coef_temp(1));
        y(4*n-50) = quantizer_input(x(4*n-38))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(4*n-39))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-40))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-41))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-42))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-43))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-44))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-45))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-46))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-47))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-48))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-49))*quantizer_coef(coef_temp(1));
        y(4*n-49) = quantizer_input(x(4*n-37))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(4*n-38))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-39))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-40))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-41))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-42))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-43))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-44))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-45))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-46))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-47))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-48))*quantizer_coef(coef_temp(1));
        y(4*n-48) = quantizer_input(x(4*n-36))*quantizer_coef(coef_temp(1))+...
                   quantizer_input(x(4*n-37))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-38))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-39))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-40))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-41))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-42))*quantizer_coef(coef_temp(6))+...
                   quantizer_input(x(4*n-43))*quantizer_coef(coef_temp(5))+...
                   quantizer_input(x(4*n-44))*quantizer_coef(coef_temp(4))+...
                   quantizer_input(x(4*n-45))*quantizer_coef(coef_temp(3))+...
                   quantizer_input(x(4*n-46))*quantizer_coef(coef_temp(2))+...
                   quantizer_input(x(4*n-47))*quantizer_coef(coef_temp(1));
end
y_1st = y(1)
y_100st = y(100)
y_200st = y(200)